#!/usr/bin/env python3
import os
import sys


def main():
    script_dir = os.path.dirname(os.path.realpath(__file__))
    source_root = os.path.dirname(script_dir)
    for path in (script_dir, source_root):
        if path not in sys.path:
            sys.path.insert(0, path)

    from ur3e_api_node.api_node import main as node_main

    node_main()


if __name__ == "__main__":
    main()
